theme = "onedark"

[editor]
line-number = "relative"

[editor.whitespace.render]
space = "none"
newline = "all"
tab = "all"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[keys.insert]
j = {k = "normal_mode"}

