[theme]
name = "slick"
[theme.overrides]
idle_bg = "#00000000"
info_bg = "#00000000"
good_bg = "#00000000"
warning_bg = "#00000000"
critical_bg = "#00000000"
separator_bg = "#00000000"
alternating_tint_bg = "#00000000"
separator = " "

[icons]
name = "awesome"
[icons.overrides]
music = " "

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
marquee = false

[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}/{MTg} GB"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°C"

[[block]]
block = "net"
device = "enp3s0"
ssid = true
ip = false
speed_up = true
speed_down = true
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %Y-%M-%d %R"
