[theme]
name = "slick"
[theme.overrides]
idle_bg = "#00000000"
info_bg = "#00000000"
good_bg = "#00000000"

warning_bg = "#00000000"
warning_fg = "#f7be00"

critical_bg = "#00000000"
critical_fg = "#ffb1c0"

separator_bg = "#00000000"
alternating_tint_bg = "#00000000"
separator = " "

[icons]
name = "awesome"
[icons.overrides]
music = " "

[[block]]
block = "music"
player = "spotify"
marquee = false

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}/{MTg} GB"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = " %a %Y-%M-%d %R"
