[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#00000000"
idle_fg = "#ffffff"
info_bg = "#00000000"
info_fg = "#ffffff"
good_bg = "#00000000"
good_fg = "#ffffff"

warning_bg = "#00000000"
warning_fg = "#f7be00"

critical_bg = "#00000000"
critical_fg = "#ffb1c0"

separator_bg = "#00000000"
alternating_tint_bg = "#00000000"
separator = " | "

[icons]
icons = "awesome4"
[icons.overrides]
music = " "


[[block]]
block = "music"
player = "spotify"
# buttons = ["play", "next"]
# marquee = false

# [[block]]
# block = "docker"
# interval = 2
# format = "{running}/{total}"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "
# on_click = "alacritty -e nmtui"
# interface_name_exclude = ["br\\-[1-9a-f]{12}", "docker\\d+"]
# interface_name_include = []

[[block]]
block = "cpu"
interval = 1
format = " $utilization.eng(u:%,w:3) $frequency.eng(w:3) "

[[block]]
block = "temperature"
interval = 10
format = " $icon $max.eng(w:2) "
chip = "*-isa-*"
inputs = ["SYSTIN", "CPUTIN"]

[[block]]
block = "memory"
format = "$icon $mem_used.eng(w:2,p:G)/$mem_total.eng(w:2,p:G) GB"

[[block]]
block = "disk_space"
path = "/"
format = " $icon $available.eng(w:4,p:G) / $total.eng(w:4,p:G) "
alert_unit = "GB"

[[block]]
block = "sound"
natural_mapping = true
format = " $icon $output_name{ $volume|}"
[block.mappings]
"alsa_output.pci-0000_2a_00.1.hdmi-stereo-extra1" = "Monitor"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R', l:en_AU) "
